### ISSUE TITLE
No scheduler is ever set

### ISSUE THREAD

**Issue by thomasjo** [nathansobo/etch#1]
The result is that any call to `etch.update`, or attempts to use `etch.observe` fails with 
```
Cannot read property 'updateDocument' of null
```
which originates in `element-prototype.js` from the `update` function
```js
update: {
  value: function () {
    if (!this._updateRequested) {
      this._updateRequested = true
      getScheduler().updateDocument(() => {
        this._updateRequested = false
        this.updateSync()
      })
    }
  }
}
```
Since `setScheduler` is never called, `getScheduler` obviously returns `null`. Similar failure occurs when attempting to use `etch.observe`.

The tests are passing because there's a `TestScheduler` wired up as part of the test harness setup.

**Comment by nathansobo** [comment]
Yeah, looks like an oversight. Now I instantiate the default scheduler if none is assigned when `getSchedelur` is called. Let me know if there are any additional issues with this approach.
