### ISSUE TITLE
Wasn't able to properly render component with atom-text-editor inside

### ISSUE THREAD

**Issue by armed** [nathansobo/etch#5]
Hi. 

I like etch, thanks for this great lib. Recently I tried to create component, but didn't know how to pass attributes to atom-text-element in render method. I wrote a test to reproduce issue:
```jsx
'use babel'
/** @jsx etch.dom */

import etch from 'etch'

describe('atom-text-editor and it\'s arguments', () => {
  it('should respect mini', () => {
    class TestComponent {
      constructor() {
        etch.createElement(this)
      }
      render() {
        return (
          <div className='some-class'>
            <atom-text-editor mini></atom-text-editor>
          </div>
        )
      }
    }

    let component = new TestComponent()

    expect(component.element.innerHTML)
      .toEqual('<atom-text-editor mini class="editor mini" tab-index="-1"></atom-text-editor>')
  })
})
```
Above test is failing with result:
```
atom-text-editor and it's arguments
  it should respect mini
    Expected '<atom-text-editor class="editor" tabindex="-1"></atom-text-editor>' 
    to equal '<atom-text-editor mini class="editor mini" tab-index="-1"></atom-text-editor>'
```

Did I miss something?

**Comment by nathansobo** [comment]
Hi @armed. That's a gotcha I should cover in the README. The "attributes" you assign in JSX are actually assigned to the DOM node as properties. In the case of the editor, we still need to link the `mini` property and attribute together as is the case with most DOM APIs. For now, to assign an attribute from JSX you need to pass the `attributes` property like this...

```js
<atom-text-editor attributes={mini: true}>
```

In this case it's awkward because `atom-text-editor` should handle mini, but overall I think it's the right tradeoff so you can pass anything as JSX attributes, not just strings.

**Comment by armed** [comment]
HI @nathansobo, thanks for clarification.

**Comment by zmb3** [comment]
Has something changed here?  The suggestion solution doesn't even compile for me.

```
render () {
   return (
        <atom-text-editor attributes={mini: true} /> // > Parsing error: unexpected token :
  )
}
```

**Comment by BinaryMuse** [comment]
@zmb3 That's not valid JSX as `mini: true` is not a valid JS expression. You'll need to make it an object: `<atom-text-editor attributes={{mini: true}} />`

**Comment by nathansobo** [comment]
You should be able to instantiate an editor directly via its constructor in your JSX rather than via that tag name. Do something like this...

```
// in your imports section
import {TextEditor} from 'atom'

// in your JSX
<TextEditor mini={true} =>
```

**Comment by zmb3** [comment]
Thanks Nathan. Works like a charm.
