### ISSUE TITLE
Issue with atom-text-editor not updating

### ISSUE THREAD

**Issue by lukemurray** [nathansobo/etch#7]
Hi, I'm trying out Etch and so far liking it, but I converted one view to it and having trouble with an <atom-text-editor> element.

If you check out https://github.com/lukemurray/data-atom/blob/master/lib/views/new-connection-dialog.js you'll see (install the package from master) that I am watching for changes on all the text editors either to build the URL when the user changes the separate values or if the type/paste a URL I break it up.

If I use ```{this.buildURL()}``` or ```{this.state.builtUrl}``` elsewhere like just in a ```<div>``` or in a normal ```<input>``` it will work. The only way I can get ```<atom-text-editor>``` to update is use ```this.ref.elementName.getModel().setText()``` but that seems backwards for Etch.

Not really sure what is happening, I can't find anything wrong with my code, although I'm new to Etch so I might be abusing it.

Any ideas?

**Comment by lukemurray** [comment]
So this may not be Etch's fault, it might be how the ```<atom-text-editor>``` works. But I was hoping to use the same pattern that Etch enables.

Setting innerHTML in on the element doesn't update it either, which is all Etch is doing I believe. Happy to close this unless you have any ideas.

**Comment by thomasjo** [comment]
As we discussed on Slack, I don't think the current design of Atom's `TextEditor` supports this level of DOM interaction. The actual state of the editor element is hidden away in a model object.

You miiiiight be able to create a custom element that is essentially a composition (or wrapper around) of the `<atom-text-editor`> element, that deals with the interaction between `innerHTML` and e.g. `setText()` on the element's model.

Whether that's worth the effort or not, is unknown. But maybe something to investigate? Or perhaps we could tweak this in Atom to support your scenario.

**Comment by lukemurray** [comment]
Thanks, I now get it hence I closed the issue. 




I don't think it's worth it for me to create a wrapper. I might look at a PR to atom if I ever get time but probably just move on :)




Thanks for your help.

**Comment by nathansobo** [comment]
At some point I'd like to improve the element interface of `atom-text-editor`. For now though, interacting with the editor via its model is probably your best bet. Just call `getModel()` on the element and use the API from there. Admittedly though, it doesn't mesh well with the DOM-diffing pattern.
