### ISSUE TITLE
lifecycle events

### ISSUE THREAD

**Issue by dasher** [nathansobo/etch#8]
I'm experimenting with using etch for an Atom plugin.
I'm trying to use a bootstrap plugin (http://www.bootstrap-switch.org/examples.html) which turns checkboxes into nifty toggle buttons.

Like most of these types of plugins, you create the elements and then call init to activate the plugin.
In render I'm iterating through a list to add checkboxes but I'm having an issue with calling the init on the plugin.

A snippet showing how I am currently doing things..

```
export default class AtomPackageTestView {
    constructor(transports) {
        this.providers = transports;
        etch.createElement(this);
        // jquery and bootstrap helpers/plugins
        jQuery = window.jQuery = require("jquery");
        require("C:/Users/dashe/.atom/packages/atom-debug-service/bower_components/bootstrap/dist/js/bootstrap.js");
        require("C:/Users/dashe/.atom/packages/atom-debug-service/assets/bootstrap-switch.js");
    }
    render() {
        return ( <div className = 'atom-debug-service padded native-key-bindings'
            tabIndex = '-1' > {
                this.renderHeading()
            } {
                this.renderLogProviders()
            } </div>
        )
    }
```

At some point I need to call jQuery(".toggle-button").bootstrapSwitch(); but I'm unclear on how to achieve this with etch without some kind of lifecycle callback once render has completed or using yet another external plugin that taps into the dom mutation events.  I don't really want to resort to nextTick..

**Comment by nathansobo** [comment]
Can you perform this action in the constructor (`etch.createElement` is synchronous) by creating your jQuery wrapper around the element itself?

```js
constructor () {
  etch.createElement(this)
  $(this.element).find('.toggle-button').bootstrapSwitch()
}
```

You could perform a similar action when the promise returned by `etch.updateElement` is resolved.

Would this work?

**Comment by dasher** [comment]
Humm, I thought I'd tried that, but maybe I'd tried using a (string) selector passed into the initial jQuery object rather than using this.element.

Using this.element works :)  thanks

**Comment by nathansobo** [comment]
Yeah, it's not necessarily on attached to the global `document` when the constructor runs, but the `element` is created synchronously.
